name: Build Application

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest # 使用 macOS 运行器可以同时构建 Mac 和 Windows

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install --verbose
          npm run postinstall || true

      - name: Create Build Resources
        run: |
          mkdir -p build
          # 创建默认图标文件（如果需要）
          touch build/icon.ico
          touch build/icon.icns

      - name: Pre-build Checks
        run: |
          echo "Checking required files..."
          if [ ! -f "main.js" ]; then
            echo "Error: main.js not found!"
            exit 1
          fi

          if [ ! -f "package.json" ]; then
            echo "Error: package.json not found!"
            exit 1
          fi

      - name: Build Application
        run: |
          echo "Starting build process..."
          export DEBUG=electron-builder
          npm run build:all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List Build Output
        if: always()
        run: |
          echo "Build output contents:"
          ls -la dist/ || echo "dist/ directory not found"

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: releases
          path: |
            dist/*-setup.exe
            dist/*.dmg
            dist/*-win.zip
            dist/*-mac.zip
            dist/latest*.yml
          if-no-files-found: error
