name: Build Application

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      platform:
        description: '选择构建平台'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - windows
          - mac

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.platform }}" = "windows" ]; then
              npm run build:windows
            elif [ "${{ github.event.inputs.platform }}" = "mac" ]; then
              npm run build:mac
            else
              npm run build -- --all
            fi
          else
            npm run build -- --all
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List Build Output
        run: ls -R dist/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: |
            dist/*-setup.exe
            dist/*.dmg
            dist/*-win.zip
            dist/*-mac.zip
            dist/latest.yml
            dist/latest-mac.yml
